### ISSUE TITLE
Missing fields on ThreeDSEnrollment.java

### ISSUE THREAD

**Issue by kdrakon** [checkout/checkout-sdk-java#133]
### Environment

* Checkout SDK version: 5.0.0

### Description
In [ThreeDSEnrollment.java](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/ThreeDSEnrollment.java), there are a few fields missing from the official API documentation ([here](https://api-reference.checkout.com/#operation/getPaymentDetails))

### Possible solution

Map the rest of the fields into the Java class

- [X] I may be able to implement this bug fix

**Comment by rsaestrela** [comment]
Hi @kdrakon, thanks for opening this issue.

The class you linked is being used in [PaymentResponse](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/response/PaymentResponse.java). The `getPaymentDetails` operation returns a [GetPaymentResponse ](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/response/GetPaymentResponse.java) that links a [ThreeDSData ](https://github.com/checkout/checkout-sdk-java/blob/master/src/main/java/com/checkout/payments/ThreeDSData.java) object that includes the fields you mentioned. So, in order to get that information, you'll have forcibly to request for the payment details. Please let me know if I'm missing something.

**Comment by kdrakon** [comment]
Hi @rsaestrela,

I can get the information in `GetPaymentResponse`, but according to the API documentation [here](https://api-reference.checkout.com/#operation/requestAPaymentOrPayout), the 3DS data is also meant to be available on `PaymentResponse` or in other words, `POST /payments`.

(Sorry, I just realised I linked to the wrong API docs in my issue description above).

_screenshot from https://api-reference.checkout.com/#operation/requestAPaymentOrPayout_
![image](https://user-images.githubusercontent.com/1347374/143513384-55364852-1ab8-40d6-8965-28c758ca6748.png)

**Comment by rsaestrela** [comment]
Hi! I suspect you're looking at the Request spec instead of the response for this operation.

![request](https://user-images.githubusercontent.com/3053481/143579086-3ba2a135-4de7-41f8-a64f-63266dbba267.PNG)

On the `POST /payments` I've never seen the API responding with the extra 3ds fields, and honestly I couldn't find any piece of documentation that proves that. Please let me know if in your use case, the API is actually returning these fields - we can add them if there's something wrong with the documentation. Actually both classes share common properties, in that case we could just have 1 mapping class for both use cases. Just to clarify, there are 3 different mapping classes for 3ds:

- `ThreeDSRequest` used at `PaymentRequest` level
- `ThreeDSData` complete 3ds information returned by the `GetPaymentResponse` on `GET /payment`
- `ThreeDSEnrollment` partial 3ds information returned in `PaymentResponse` on `POST /payments`

If it helps, please have a look on the [OAS repository](https://github.com/checkout/checkout-api-reference/tree/master/abc_spec/components/schemas/Payments) (the UI is generated from that spec).

Again, please let me know if I'm missing something. These mappings can get tricky sometimes.

**Comment by kdrakon** [comment]
🤦‍♂️ you're right, I was mistakingly looking at the request object, not the response! Sorry about that, I will close this issue now.
