### ISSUE TITLE
When receiving webhook notification, links are not populated in body

### ISSUE THREAD

**Issue by spinxas** [checkout/checkout-sdk-java#220]
### Environment

* Checkout SDK version: 3.7.0
* Platform and version: Java 11
* Operating System and version: AWS EC2 (Code Deploy)

### Description

Receiving the webhook notification, when doing EventReponse.toString:
`EventResponse(super=Resource(links={}, apiResponseInfo=null), id=evt_onvtqgdbw6curni7ihxi656il4, type=payment_refunded, version=1.0.12, createdOn=null, data={id=pay_gvw2v3jsqs5ehhqlq6bx5mqxeq, action_id=act_qklvzmfjzzrehgt3zustqcccea, reference=530999799294, amount=3000, processed_on=2022-05-17T13:57:02.8313545Z, response_code=10000, response_summary=Approved, balances={total_authorized=3000, total_voided=0, available_to_void=0, total_captured=3000, available_to_capture=0, total_refunded=3000, available_to_refund=0}, metadata={}, currency=GBP, processing={acquirer_transaction_id=732721172871362484022, acquirer_reference_number=33030362117614996567884}}, notifications=null)`
or using GsonSerializer.toJson:
`{"id":"evt_onvtqgdbw6curni7ihxi656il4","type":"payment_refunded","version":"1.0.12","data":{"id":"pay_gvw2v3jsqs5ehhqlq6bx5mqxeq","action_id":"act_qklvzmfjzzrehgt3zustqcccea","reference":"530999799294","amount":3000,"processed_on":"2022-05-17T13:57:02.8313545Z","response_code":"10000","response_summary":"Approved","balances":{"total_authorized":3000,"total_voided":0,"available_to_void":0,"total_captured":3000,"available_to_capture":0,"total_refunded":3000,"available_to_refund":0},"metadata":{},"currency":"GBP","processing":{"acquirer_transaction_id":"732721172871362484022","acquirer_reference_number":"33030362117614996567884"}},"_links":{}}`
in both instances the links are not populated, while looking at webhook.site the links are there:
`{
  "id": "evt_onvtqgdbw6curni7ihxi656il4",
  "type": "payment_refunded",
  "version": "1.0.12",
  "created_on": "2022-05-17T13:57:05.9639092Z",
  "data": {
    "id": "pay_gvw2v3jsqs5ehhqlq6bx5mqxeq",
    "action_id": "act_qklvzmfjzzrehgt3zustqcccea",
    "reference": "530999799294",
    "amount": 3000,
    "processed_on": "2022-05-17T13:57:02.8313545Z",
    "response_code": "10000",
    "response_summary": "Approved",
    "balances": {
      "total_authorized": 3000,
      "total_voided": 0,
      "available_to_void": 0,
      "total_captured": 3000,
      "available_to_capture": 0,
      "total_refunded": 3000,
      "available_to_refund": 0
    },
    "metadata": {},
    "currency": "GBP",
    "processing": {
      "acquirer_transaction_id": "732721172871362484022",
      "acquirer_reference_number": "33030362117614996567884"
    }
  },
  "_links": {
    "self": {
      "href": "https://api.sandbox.checkout.com/workflows/events/evt_onvtqgdbw6curni7ihxi656il4"
    },
    "subject": {
      "href": "https://api.sandbox.checkout.com/workflows/events/subject/pay_gvw2v3jsqs5ehhqlq6bx5mqxeq"
    }
  }
}`

### Expected behavior

The links would be populated when receiving the webhook notification. This allows to match CKO-Signature key.

### Current behavior
Links are not populated and we fail to match CKO-Signature as when hashing the response body our hashed value is different than the provided header.

### Steps to reproduce
Controller used:
```
    /**
     * POST /acquirer/checkout/webhook/event : handleAcquirerEventForCheckout
     *
     * @param eventResponse EventResponse (required)
     * @param ckoSignature Cko-Signature (optional)
     * @return Event successfully invoked. (status code 200)
     *         or Internal Server Error. (status code 500)
     */
    @ApiOperation(value = "handleAcquirerEventForCheckout", nickname = "handleAcquirerEventForCheckout", notes = "", response = String.class, tags={ "acquirer-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Event successfully invoked.", response = String.class),
        @ApiResponse(code = 500, message = "Internal Server Error.", response = RestError.class) })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/acquirer/checkout/webhook/event",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<String> handleAcquirerEventForCheckout(@ApiParam(value = "EventResponse", required = true) @Valid @RequestBody com.checkout.events.EventResponse eventResponse,@ApiParam(value = "Cko-Signature") @RequestHeader(value = "Cko-Signature", required = false) String ckoSignature) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```

    
and the implementation:

```
@Override
    public ResponseEntity<String> handleAcquirerEventForCheckout(EventResponse eventResponse, String ckOSignature) {
        log.info("handleAcquirerEventForCheckout:+ Event received from acquirer checkout, event: {}", eventResponse.toString());
        acquirerWebhookEventService.handleAcquirerEventForCheckout(eventResponse, ckOSignature);
        log.info("handleAcquirerEventForCheckout:- Event successfully invoked.");
        return ResponseEntity.ok().body("Event successfully invoked.");
    }
```

### Possible solution

- [ ] I may be able to implement this bug fix

**Comment by Armando-Ibarra** [comment]
Hi @spinxas, thank you for the provided information.
This seems to be more a problem of the API than the SDK, I used SDK version to retrieve an event and I was able to see the links
![image](https://user-images.githubusercontent.com/30295119/169070891-0c74be49-31ff-4ec4-b786-34250c25f2d8.png)

ToString
`EventResponse(super=Resource(links={self=Link(href=https://api.sandbox.checkout.com/events/evt_42yzenx6cxvuhcc5wjhvfy7p3m, title=null), webhooks-retry=Link(href=https://api.sandbox.checkout.com/events/evt_42yzenx6cxvuhcc5wjhvfy7p3m/webhooks/retry, title=null)}, apiResponseInfo=ApiResponseInfo(httpStatusCode=200, requestId=0HMHK6L06C8Q3:00000001)), id=evt_42yzenx6cxvuhcc5wjhvfy7p3m, type=payment_approved, version=2.0, createdOn=2022-05-18T13:01:14Z, data={action_id=act_vs34udzg4o7kphpw3gx7lyuche, payment_type=REGULAR, auth_code=092532, response_code=10000, response_summary=Approved, scheme_id=469946167982122, source={id=src_jge3lfkxoote3cy7r5xkr65ybm, type=card, billing_address={address_line1=CheckoutSdk.com, address_line2=90 Tottenham Court Road, city=London, state=London, zip=W1T 4TJ, country=GB}, phone={country_code=44, number=020 222333}, expiry_month=6.0, expiry_year=2025.0, name=Mr. Duke, scheme=VISA, last_4=4242, fingerprint=9f3bad2e48c6c8579f2f5dc0710b7c11a8acd5072c3363a72579a6fb227d64be, bin=424242, card_type=Credit, card_category=Consumer, issuer_country=GB, product_id=F, product_type=Visa Classic, avs_check=S, cvv_check=Y}, customer={id=cus_ispfwhxc4bnetdhqdggy6yhjfu}, processing={acquirer_transaction_id=8457623543, retrieval_reference_number=017701982009}, amount=10.0, metadata={}, risk={flagged=false}, id=pay_vs34udzg4o7kphpw3gx7lyuche, currency=GBP, processed_on=2022-05-18T13:01:14Z, reference=0761e4cd-4c82-4d3f-ad39-e6511cedb093}, notifications=[])`

Could you please try the following command in your terminal and share the result of the command, replace `event_id` and `secret_key`.
There is no need to share the curl command because it will contains sensitive information like your secret_key, I just need to double check the result.

curl --location --request GET 'https://api.checkout.com/events/event_id' \
--header 'Authorization: secret_key'

**Comment by Armando-Ibarra** [comment]
Closed due inactivity
